### ISSUE TITLE
Feature request to add a new option.

### ISSUE THREAD

**Issue by shohagkhan** [fayras/vscode-simple-new-file#14]
Thanks for the awesome extension. I think most people don't know about this very useful vscode extension. I have one feature request.
1. If possible please give the option to add plus, delete and folder sign to create and delete new file and folder on the right side of every folder name in the folder tree. You can also add a delete sign on the right side of every file.
Thanks again for your very good afford.
![image](https://user-images.githubusercontent.com/16593128/145676852-b15746ce-efde-42af-836b-82ae44c308e9.png)

**Comment by fayras** [comment]
Thanks! Glad you like the extension.

Regarding your feature request: I'm afraid that is outside the scope of this project. I would like to keep this extension simple.
