### ISSUE TITLE
Custom shortcut to go "up" a directory?

### ISSUE THREAD

**Issue by aguynamedben** [fayras/vscode-simple-new-file#15]
Hi, I'm coming from Emacs and this is an incredible missing piece to replace `C-x C-f` from Emacs.

Is there a way I can configure it so that `C-l` (Command + L) will go "up" a directory? I realize I can just hit `Enter`, but I'm so used to hitting `C-l` to go "up" in Emacs.

Thanks for contributing this!

**Comment by fayras** [comment]
Hi. I'm glad you find the extension useful!

Selecting the file/up via a shortcut would be quite a nice feature, actually. 
I've dug into the VS Code Extension API and unfortunately the picker does not support shortcuts and VS Code does not expose keypresses to extensions in general.
