### ISSUE TITLE
no longer works on vscode 1.88.0

### ISSUE THREAD

**Issue by AriaRahmati** [fayras/vscode-simple-new-file#18]
I'm not sure at which version it stopped working for me, but currently I'm on 

Version: 1.88.0 (user setup)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:26:18.741Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

and it's not creating files anymore

**Comment by AriaRahmati** [comment]
![image](https://github.com/fayras/vscode-simple-new-file/assets/49791896/bb488e38-20ac-4fd0-a9eb-0520636c351d)

The only way that it creates a file is by proving the path and file name as the default path in the extension settings.

**Comment by agilso** [comment]
It has stopped working for me as well. The extension window shows up, but the file isn't getting created. VS Code's developer tool is reporting a 'TypeError: Cannot read properties of undefined (reading 'normalize')'.

- VS Code Version: 1.88.0 (Universal)
- macOS - Sonoma 14.4.1
- MacBook Pro - Apple Silicon M1 chip

**Comment by mattfysh** [comment]
same issue as https://github.com/fayras/vscode-simple-new-file/issues/17

i don't think the author is actively maintaining the extension anymore, which is a shame as it's the best one out there. i tried switching to a few others but none of them also offered the ability to use the dropdown to open existing files. the most popular one also had a a weird two-step process where you had to first specify the folder first, then the filename

im hoping the break is related to the april vscode release, and that it will go back to working again once they release the next update in may. if not, i might dig in and try to get the extension working again. anyone else interested in helping out?

**Comment by AriaRahmati** [comment]
> same issue as https://github.com/fayras/vscode-simple-new-file/issues/17
> 
> i don't think the author is actively maintaining the extension anymore, which is a shame as it's the best one out there. i tried switching to a few others but none of them also offered the ability to use the dropdown to open existing files. the most popular one also had a a weird two-step process where you had to first specify the folder first, then the filename
> 
> im hoping the break is related to the april vscode release, and that it will go back to working again once they release the next update in may. if not, i might dig in and try to get the extension working again. anyone else interested in helping out?

Exactly, I experienced the same, the two-step process is annoying and I couldn't find any other extension that works as well as SimpleNewFile. I really hope whether it works in the future updates or we can create a fork and try to solve the issue.

**Comment by mattfysh** [comment]
It looks like everything is back to normal with the latest vscode release?

**Comment by AriaRahmati** [comment]
> It looks like everything is back to normal with the latest vscode release?

Yes, It seems that the problem is solved and I'm not experiencing any issues working with the extension.
