### ISSUE TITLE
Option to default to project root

### ISSUE THREAD

**Issue by stdavis** [fayras/vscode-simple-new-file#2]
Thanks for the great extension!

Is there an option that I can switch on to default the new path always be relative to the root of my project?

**Comment by fayras** [comment]
Sorry for the delayed response!

Currently there is no such option.
I'd be willing to implement it. Perhaps an option to set a default path which will be inserted whenever you bring up the prompt. 

```js
{
  "defaultPath": "/"
  // or
  "defaultPath": "/src/"
}
``` 

The first entry would cover your case. Further, you would be able to set a default path (on a per project basis?) to always start in your specified location. 

Not sure whether this would be a useful feature or not.

**Comment by stdavis** [comment]
I like it!
