### ISSUE TITLE
Can no longer use outside project root

### ISSUE THREAD

**Issue by mattfysh** [fayras/vscode-simple-new-file#4]
Previously I could have a file outside of the project root open, and when bringing up the Simple New File list it would show all files in the same directory as the active file.

E.g. if I had a project root at `/Projects/foo` as well as a todo file at `/Projects/todo.md`, when the todo.md file was open I could use the Simple New File list to quickly open files that were in the same directory as todo.md

Not sure if this is related to the latest vscode release - but this no longer works, the list that comes up is empty

**Comment by fayras** [comment]
Fixed in 1.1.2
