### ISSUE TITLE
Incorrect match

### ISSUE THREAD

**Issue by mattfysh** [fayras/vscode-simple-new-file#5]
If I have a file called `service.ts` and I try to use Simple New File to create a new directory + file, such as `services/foo.ts`, I can no longer do so - it seems to open up `service.ts` instead.

**Comment by fayras** [comment]
Hi.
Unfortunatly I'm busy with university stuff right now but I will definitely have a look into this. 
Sorry for the delay!

**Comment by fayras** [comment]
I am unable to reproduce this issue. 
If you still experience this problem, please let me know.
