### ISSUE TITLE
Odd file entries in Quick Open after relative file creation

### ISSUE THREAD

**Issue by craig-jennings** [fayras/vscode-simple-new-file#6]
1. Create the following directory structure

```
test
| -- sub
     | -- test-1.txt
```

2. Open the `test` directory in vscode
2. Open the test-1.txt file
2. While focused on that file, trigger the extension. Navigate to the `test` directory using `../`. Set the name of the new file to anything (I used `test-2.txt`)
2. Open the Quick Open panel (`Ctrl + p`) and type the name of the new file
2. Notice that there are now two entries, one with a path relative to the root and the other with a relative path that was defined during creation
2. Also notice the filepath contains relative information instead of the path from the root directory

![image](https://user-images.githubusercontent.com/1683368/67024161-91663c80-f0c9-11e9-989a-82a0ee2bda83.png)

This actually seems to cause VSCode to be confused about the files. You can open both `test-2.txt` entries and it will open two different tabs. Changing the contents of one file isn't reflected in the other file. It's like vscode treats them as two different files even though on the file system it's one file.

**Comment by fayras** [comment]
I'm unable to reproduce this.
Looking at the linked issues, it does seem to have been an issue with vscode itself. Feel free to reopen this issue if updating vscode did not resolve it.
